<?php
/*
$this->headerTitle = 'teste';
$this->headerSubtitle = 'teste';
$this->headerMenu = $this->AddLink();
*/
?>

<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-primary">
			<div class="panel-heading"><h3 class="panel-title"><i class="fa fa-user"></i> Teste</h3></div>
			<div class="panel-body">
				<table class="table">
					<thead>
					<tr>
						<th>Matrícula</th>
						<th>Senha</th>
						<th>Perfil</th>
					</tr>
					</thead>
					<tbody>
					<?php if ( $this->data ): ?>
						<?php foreach ( $this->data as $row ): ?>
							<tr>
								<td><?php echo $row['SIRH_TB001_MATRICULA'] ?></td>
								<td><?php echo $row['SCSA_TB009_SENHA'] ?></td>
								<td><?php echo $row['SCSA_TB009_PERFIL'] ?></td>
							</tr>
						<?php endforeach; ?>
					<?php endif; ?>
					</tbody>
				</table>

			</div>
			<div class="panel-footer padding-0">
				<?php echo $this->data ?>
			</div>
		</div>
	</div>
</div>