<?php
$this->headerTitle = 'Título';
$this->headerSubtitle = 'Subtítulo';
$this->headerMenu = $this->Dropdown( 'Dropdown' )
    ->addHeader( 'Teste' )
    ->addAnchor( '<a role="menuitem" tabindex="-1" href="#">Action</a>', true )
    ->addDivider()
    ->addItem( '<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>' );

echo $this->Alert();
echo $this->Navs( array( 'Index' => 'index', 'Edit' => 'teste' ) );
echo $this->Callout()->setType( 'danger' );



?>