<?php if ( $this->pageCount ): ?>
	<nav class="text-center">
		<ul class="pagination">
			<?php if ( isset( $this->previous ) ): ?>
				<li class="">
					<a href="<?php echo $this->url( array( 'page' => $this->first ) ); ?>" title="Primeira">
						<span class="glyphicon glyphicon-step-backward"></span>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url( array( 'page' => $this->previous ) ); ?>" title="Anterior">
						<span class="glyphicon glyphicon-backward"></span>
					</a>
				</li>
			<?php else: ?>
				<li class="disabled">
					<a href="#"><span class="glyphicon glyphicon-step-backward"></span></a>
				</li>
				<li class="disabled">
					<a href="#"><span class="glyphicon glyphicon-backward"></span></a>
				</li>
			<?php endif; ?>
			<?php foreach ( $this->pagesInRange as $page ): ?>
				<?php if ( $page != $this->current ): ?>
					<li>
						<a href="<?php echo $this->url( array( 'page' => $page ) ); ?>"><?php echo $page; ?></a>
					</li>
				<?php else: ?>
					<li class="active">
						<a href="#"><?php echo $page; ?></a>
					</li>
				<?php endif; ?>
			<?php endforeach; ?>
			<?php if ( isset( $this->next ) ): ?>
				<li>
					<a href="<?php echo $this->url( array( 'page' => $this->next ) ); ?>" title="Próxima">
						<span class="glyphicon glyphicon-forward"></span>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url( array( 'page' => $this->last ) ); ?>" title="Última">
						<span class="glyphicon glyphicon-step-forward"></span>
					</a>
				</li>
			<?php else: ?>
				<li class="disabled">
					<a href="#"><span class="glyphicon glyphicon-forward"></span></a>
				</li>
				<li class="disabled">
					<a href="#"><span class="glyphicon glyphicon-step-forward"></span></a>
				</li>
			<?php endif; ?>
		</ul>
	</nav>
<?php endif; ?>
