<!-- BEGIN FOOTER -->
<div class="footer">
	<div class="container">
		<div class="row">
			<!-- BEGIN SOCIAL MEDIA -->
			<div class="col-md-3 col-sm-3">
				<ul class="social-footer list-unstyled list-inline pull-left margin-top-10">
					<li><a href="#"><i class="fa fa-facebook"></i></a></li>
					<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
					<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
					<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter"></i></a></li>
					<li><a href="#"><i class="fa fa-skype"></i></a></li>
					<li><a href="#"><i class="fa fa-github"></i></a></li>
					<li><a href="#"><i class="fa fa-youtube"></i></a></li>
					<li><a href="#"><i class="fa fa-dropbox"></i></a></li>
				</ul>
			</div>
			<!-- END SOCIAL MEDIA -->

			<!-- BEGIN COPYRIGHT -->
			<div class="col-md-6 col-sm-6">
				<p class="text-muted margin-top-10 text-center">
					2015 - ALL Rights Reserved. <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a>
				</p>
			</div>
			<!-- END COPYRIGHT -->

			<!-- BEGIN SUBSCRIBE -->
			<div class="col-md-3 col-sm-3 pull-right">
				<div class="input-group input-group-sm">
					<input type="text" placeholder="youremail@mail.com" class="form-control">
                  <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">
						<?php echo $this->translate( 'subscribe' ) ?>
					</button>
                  </span>
				</div>
			</div>
			<!-- END SUBSCRIBE -->
		</div>
	</div>
</div>
<!-- END FOOTER -->