<?php if ( $this->title || $this->menu ): ?>
    <h1 class="page-header">
        <div class='pull-right'>
            <?php echo $this->menu; ?>
        </div>
        <?php if ( $this->title ): ?>
            <span class="sub-header">
                <?php echo $this->title; ?>
                <small><?php echo $this->subtitle; ?></small>
        </span>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </h1>
<?php endif; ?>