<?php
$baseUrl = $this->baseUrl();

//css
$this->headLink()->appendStylesheet( $baseUrl . '/bootstrap3/css/bootstrap.min.css' );
//$this->headLink()->appendStylesheet( $baseUrl . '/bootstrap3/css/docs.min.css' );
$this->headLink()->appendStylesheet( $baseUrl . '/css/default.css' );

//js
$this->headScript()->appendFile( "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" );
$this->headScript()->appendFile( $baseUrl . '/bootstrap3/js/bootstrap.min.js' );
$this->headScript()->appendFile( $baseUrl . '/js/maskedinput.js' );
$this->headScript()->appendFile( $baseUrl . '/js/default.js' );
?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt_BR" lang="pt_BR">
<head>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<!--<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>-->
	<!--<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
	<!--[endif]-->
</head>
<body>

<?php echo $this->partial( 'navbar.phtml', array( 'navigation' => $this->navigation ) ); ?>

<!-- BEGIN CONTAINER -->
<div class="container">
	<?php
	echo $this->partial( 'header.phtml', array(
		'title' => $this->headerTitle,
		'subtitle' => $this->headerSubtitle,
		'menu' => $this->headerMenu
	) );
	echo $this->FlashMessenger();
	echo $this->layout()->content;
	?>
</div>
<!-- END CONTAINER -->

<?php echo $this->partial( 'footer.phtml' ); ?>

<?php echo $this->headScript() ?>
</body>
</html>