<?php
$baseUrl = $this->baseUrl();
?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt_BR" lang="pt_BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="<?php echo $baseUrl; ?>/bootstrap3/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $baseUrl; ?>/bootstrap3/css/docs.min.css" rel="stylesheet">

    <!-- style -->
    <?php echo $this->partial( 'style.phtml' ); ?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>-->
    <!--<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
    <!--[endif]-->
</head>
<body>

<?php echo $this->partial( 'navbar.phtml', array( 'navigation' => $this->navigation ) ); ?>

<!-- BEGIN CONTAINER -->
<div class="container">
    <?php echo $this->partial( 'header.phtml', array(
        'title' => $this->headerTitle,
        'subtitle' => $this->headerSubtitle,
        'menu' => $this->headerMenu
    ) ); ?>

    <?php echo $this->layout()->content; ?>
</div>
<!-- END CONTAINER -->

<?php //echo $this->partial( 'footer.phtml' ); ?>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="<?php echo $baseUrl; ?>/bootstrap3/js/bootstrap.min.js" type="text/javascript"></script>
<?php echo $this->headScript() ?>
</body>
</html>