<?php
$baseUrl = $this->baseUrl();

//load datetimerpicker files
if ( $this->datetimepicker ) {
	//css
	$this->headLink()->prependStylesheet( $baseUrl . '/assets/bootstrap3-datetimepicker/css/bootstrap-datetimepicker.min.css' );
	//js
	$this->headScript()->prependFile( $baseUrl . '/assets/bootstrap3-datetimepicker/js/bootstrap-datetimepicker.min.js' );
	$this->headScript()->prependFile( $baseUrl . '/assets/bootstrap3-datetimepicker/js/collapse.js' );
	$this->headScript()->prependFile( $baseUrl . '/assets/bootstrap3-datetimepicker/js/transition.js' );
	$this->headScript()->prependFile( $baseUrl . '/assets/bootstrap3-datetimepicker/js/moment-pt_br.min.js' );
}

//css
$this->headLink()->prependStylesheet( $baseUrl . '/css/extra.css' );
$this->headLink()->prependStylesheet( $baseUrl . '/css/default.css' );
$this->headLink()->prependStylesheet( $baseUrl . '/css/metronic.css' );
$this->headLink()->prependStylesheet( $baseUrl . '/assets/font-awesome-4.3.0/css/font-awesome.min.css' );
$this->headLink()->prependStylesheet( $baseUrl . '/assets/bootstrap3/css/bootstrap.min.css' );

//js
$this->headScript()->prependFile( $baseUrl . '/js/default.js' );
$this->headScript()->prependFile( $baseUrl . '/js/maskedinput.js' );
$this->headScript()->prependFile( $baseUrl . '/assets/bootstrap3/js/bootstrap.min.js' );
$this->headScript()->prependFile( "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" );
?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt_BR" lang="pt_BR">
<head>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<!--<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>-->
	<!--<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
	<!--[endif]-->
</head>
<body>

<?php echo $this->partial( 'navbar.phtml', array( 'navigation' => $this->navigation ) ); ?>

<!-- BEGIN CONTAINER -->
<div class="container margin-bottom-60">
	<?php
	echo $this->partial( 'header.phtml', array(
		'title' => $this->headerTitle,
		'subtitle' => $this->headerSubtitle,
		'menu' => $this->headerMenu
	) );
	?>
	<?php echo $this->FlashMessenger(); ?>

	<!-- BEGIN CONTENT -->
	<?php echo $this->layout()->content; ?>
	<!-- END CONTENT -->
</div>
<!-- END CONTAINER -->

<?php echo $this->partial( 'footer.phtml' ); ?>

<?php echo $this->headScript() ?>
</body>
</html>