<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
					aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Project name</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<?php echo $this->navigation; ?>
			<form class="navbar-form navbar-left" role="search">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="<?php echo $this->translate( 'search' ) ?>">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default"><?php echo $this->icon( 'search' ) ?></button>
                    </span>
				</div>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<?php if ( !Zend_Auth::getInstance()->hasIdentity() ): ?>
					<li><a href="#">login</a></li>
					<li><a href="#">cadastro</a></li>
				<?php else: ?>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
							<?php echo Zend_Auth::getInstance()->getIdentity()->getLogin(); ?>
							<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="#"><?php echo $this->icon( 'user' ) ?> Perfil</a></li>
							<li><a href="#"><?php echo $this->icon( 'cog' ) ?> Configurações</a></li>
							<li class="divider"></li>
							<li><?php echo $this->Link( $this->Icon( 'off' ) . ' Logout', 'index', 'logout' ) ?></li>
						</ul>
					</li>
				<?php endif; ?>
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
</nav>